Fixing main.yml on Run mlflow project steps

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -52,7 +52,11 @@ jobs:
 
       - name: Get latest MLflow run_id
         run: |
-          RUN_ID=$(grep -oP 'MLFLOW_RUN_ID=\K[a-f0-9\-]+' mlflow_output.log)
+          RUN_ID=$(grep -oP 'MLFLOW_RUN_ID=\K[a-f0-9\-]+' mlflow_output.log || true)
+          if [ -z "$RUN_ID" ]; then
+            echo "❌ Run ID not found in mlflow_output.log"
+            exit 1
+          fi
           echo "✅ Run ID: $RUN_ID"
           echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
 
